exclude:
  - 'src/'
  - '.gitignore'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'LICENSE'
  - 'node_modules'
  - 'npm-debug.log'
  - 'package.json'
  - 'README.md'
  - 'webpack.config.js'

sass:
  style: :compressed
